// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts,import_extension=none"
// @generated from file session/v1/api.proto (package session.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateSessionRequest, CreateSessionResponse } from "./api_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service session.v1.SessionService
 */
export const SessionService = {
  typeName: "session.v1.SessionService",
  methods: {
    /**
     * @generated from rpc session.v1.SessionService.CreateSession
     */
    createSession: {
      name: "CreateSession",
      I: CreateSessionRequest,
      O: CreateSessionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

