// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file integration/v1/error_details.proto (package integration.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message integration.v1.RollbackInfo
 */
export class RollbackInfo extends Message<RollbackInfo> {
  /**
   * @generated from field: string transaction_id = 1;
   */
  transactionId = "";

  constructor(data?: PartialMessage<RollbackInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "integration.v1.RollbackInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RollbackInfo {
    return new RollbackInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RollbackInfo {
    return new RollbackInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RollbackInfo {
    return new RollbackInfo().fromJsonString(jsonString, options);
  }

  static equals(a: RollbackInfo | PlainMessage<RollbackInfo> | undefined, b: RollbackInfo | PlainMessage<RollbackInfo> | undefined): boolean {
    return proto3.util.equals(RollbackInfo, a, b);
  }
}

